### ISSUE TITLE
Update artifact versions

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#24]
#### Description
Many of the tools and libraries we are using right not are quite old versions. There is a branch available that has updated versions. We should merge these changes to dev/master.

#### DoD
Working tests/pipelines with updated versions.

**Comment by blankdots** [comment]
As part of this commit:
* gm-api version 1.3 includes changes in work for new GM-API (temporary)
* gm-api and wf-api image include stdout on supervisor from console (we can view logs in docker logs - we could not previously)
* updated versions of libraries (where it did not affect the code)
* pyGradle version bump
* tests work with gradle 4.0.1 
  * pd-feature-tests
  * gc-feature-tests
  * dc-feature-tests
  * wf-feature-tests
* some tests were commented out due to the fact that certain components changed

**Comment by blankdots** [comment]
As part of this a suggestion is to update documentation regarding https://attx-project.github.io/Containerized-testing.html as it is no long accurate.

**Comment by blankdots** [comment]
also Jenkins now uses Gradle 3.5

**Comment by blankdots** [comment]
followup issue https://github.com/ATTX-project/ATTX-project.github.io/issues/66
